### ISSUE TITLE
攻 and all similar

### ISSUE THREAD

**Issue by Gnurou** [KanjiVG/kanjivg#10]
even if the radical is 工 (48) 攴 (66) does it not make more sense to use the so-called 攵 nobun/ノ-文 variant as the Component? Side note why do so many components not show up in component search display ;_; additional ones will show up depending on previous components selected. Also maybe should note that some users may be used to different styles of chinese characters. Such as 令 as mentioned above. (interesting fact calligraphy is the only legal use of traditional characters in China) Tae August 21, 2010, at 07:02 AM

**Comment by benkasminbullock** [comment]
> even if the radical is 工 (48) 攴 (66) does it not make more sense to use the so-called 攵 nobun/ノ-文 variant as the Component?

This is given as kvg:original="攵" in the source file.

> Side note why do so many components not show up in component search display ;_; additional ones will show up depending on previous components selected.

I don't know what component search display here refers to, this repository doesn't contain a component search element, so that seems to be a bug elsewhere.

Since it's not very clear what action should be taken here, I suggest closing this issue. Please reopen if not fully satisfied.
