### ISSUE TITLE
Consistency check script

### ISSUE THREAD

**Issue by Gnurou** [KanjiVG/kanjivg#126]
Some basic errors, like the one fixed by https://github.com/bdusell/kanjivg/commit/633a739d720ebc43db016f05e8bb99bf39443c2a , (ID of components not matching that of the file) could easily be detected by a script. A simple load/write script could also fix them.

**Comment by scriptin** [comment]
This feature is implemented in [kanjivg-tools](https://github.com/scriptin/kanjivg-tools), `repair_ids` task. You can copy any file, name it as you want, and then run this task on it - all IDs will be updated to match the file name.

**Comment by benkasminbullock** [comment]
Since the script exists thanks to @scriptin, I guess we can close this now?

**Comment by scriptin** [comment]
@benkasminbullock Does it still work? I haven't checked it for several years now. As long as KanjiVG format hasn't changed, it shouldwork.

**Comment by benkasminbullock** [comment]
@scriptin I am very sorry but I have not tried it. I think the format has not changed at all since around 2011. I actually wrote my own script to check that the six-year-old bug was remaining, I got exactly the same results as @bdusell, and I closed the bug about the consistency of the hex ids/kanji yesterday:

https://github.com/KanjiVG/kanjivg/commit/5b5391dd43698dcff35a4592721ac644e6dbf13f

Presumably you can get the same results with your script or another one.

If you want to reopen this issue though, we can do, so let me know.
