### ISSUE TITLE
乚 character request

### ISSUE THREAD

**Issue by erikgerrits** [KanjiVG/kanjivg#129]
https://en.wikipedia.org/wiki/Simplified_table_of_Japanese_kanji_radicals

**Comment by erikgerrits** [comment]
I noticed KanjiVG contains all radicals from the wikipedia simplified radicals table, except for 12. I think it would be nice to complete it. I've added them independently.

**Comment by ospalh** [comment]
Sounds like a good idea.
You want to do it yourself? New contributors are always welcome. :smile: 

The way to go would be something like this:

- Finde a kanji with that radical
- Copy that file to a file named after the code point, in case of 乚, unicode code point 0x4e5a, to `04e5a.svg`
- Editing the file with a text or xml editor. A graphical SVG editor like inkscape messes up the file structure.
 - Remove all strokes and groups that are *not* the radical
 - Clean up the grouping, moving the radical group up in the hierarchy.
 - Change the id attributes
 - Centere the radical. (IIRC, there was a discussion once, and the result was that radicals should be centered.) Here inkspcape can be a help. but it is best to edit a copy and cut-and-paste the path, the `d="…"` bit by hand.
 - Maybe change the shape to make it look more 
- Review, make sure everything looks fine and the internal structure is similar to that of other files.
- Open a pull request.

Of course, doing only certain steps would be a help, too.

And i think all radicals that are in use are in KanjiVG already and a quick search for “乚” as a group gave no results, so maybe the shapes have to be drawn from scratch. Or rather starting with another kanji, so that we can reuse the file structure.

**Comment by Gnurou** [comment]
Agree that this is a good idea.

Also agree that a direct contribution is the fastest way to see this addressed. ;)

**Comment by ospalh** [comment]
Maybe i will find some time to do this some soonish.
