### ISSUE TITLE
啇 character request

### ISSUE THREAD

**Issue by erikgerrits** [KanjiVG/kanjivg#140]
https://en.wikipedia.org/wiki/Simplified_table_of_Japanese_kanji_radicals

**Comment by wtn** [comment]
Here's a reference glyph: [MJ008378](https://mojikiban.ipa.go.jp/search/detail/MJ008378).

![mj008378](https://user-images.githubusercontent.com/35801/42102698-57ccfd6e-7b8c-11e8-94f1-502aad41e9cb.png)

**Comment by benkasminbullock** [comment]
啇 is not within the JIS encoding levels one and two, so it isn't in KanjiVG. There are about 20,000 other characters like this, so there is not much point requesting it here. Maybe look for a project which covers Chinese encodings.

**Comment by wtn** [comment]
This character is significant for being a component of several characters used in Japanese: 摘 嫡 敵 滴 謫 適 鏑｡

**Comment by benkasminbullock** [comment]
> This character is significant for being a component of several characters used in Japanese: 摘 嫡 敵 滴 謫 適 鏑｡

I'm not sure what argument you're making. Those characters are already within KanjiVG:

![U6458](https://user-images.githubusercontent.com/102005/115167013-d02ae780-a0f0-11eb-936c-07842e1fdf3d.png)

So including the above won't help include other existing Japanese characters.

It may be possible to add the character using some editing software to remove the left part of the above image and then stretching.

**Comment by wtn** [comment]
To expand my last comment a bit, this character appears in *Remembering the Kanji* and similar methods, as a component of 嫡 etc. So it's arguably at least as useful for learners as most JIS level two characters.

![antique](https://user-images.githubusercontent.com/35801/115171221-34659100-a088-11eb-8927-41aece889303.jpg)

This character also appears in kanji dictionaries such as 漢辞海 and 新字源｡

Arguments can be made for including this character or not; it's up to the project to define scope.

**Comment by benkasminbullock** [comment]
I don't know why you think that there is some army of people adding things to this project. The original KanjiVG content was all created by Ulrich Apel around 2005, and then released later on in 2008 or so. Since then no-one has been creating any new characters for the collection. 

Since it is 13 years from the original release of the information, and the original project finished 16 years ago, you can ask for new characters here, but who do you expect will create them? If people want new elements they really need to go ahead and add them. Discussing how the project scope is defined, or requesting new characters, will achieve very little.

**Comment by wtn** [comment]
Thank you for your comment. Please note that I didn't open this Github issue and I have no expectation that any action will be taken. I was simply providing context for why someone might want this character.
