### ISSUE TITLE
卽 and 晚 request

### ISSUE THREAD

**Issue by abajur** [KanjiVG/kanjivg#168]
晚 is the old kanji form of 晩.
卽 is the old kanji form of 即.

**Comment by benkasminbullock** [comment]
I've closed this and the other stale addition request issues, since nobody seems to want to do it, and most of these have been languishing here for six years or more. The newest one is a year ago, and despite adding most of the missing elements myself, there was no response from the requester, so I guess they have disappeared too. 

Please reopen the issue if you want to.
