### ISSUE TITLE
Missing top stroke in 饗

### ISSUE THREAD

**Issue by twwn** [KanjiVG/kanjivg#171]
The Jinmeiyō [09957/饗](https://github.com/KanjiVG/kanjivg/blob/master/kanji/09957.svg) is missing the top stroke of its upper middle component, perhaps a mistake due to 郷 being shinjitai and 鄕 kyūjitai.

It's already there in the kanji_mismatch variants, but omitted from the three "normal" files.

See eg.:

* [Wiktionary entry](https://en.wiktionary.org/wiki/饗), also giving the stroke count as 22 rather than 21

* Kodansha Kanji Learner's Course, entry 1296, again also 22 strokes

* [法務省 Jinmeiyō PDF](http://www.moj.go.jp/content/001131003.pdf), p. 3, second last kanji

**Comment by ospalh** [comment]
Oh, looks like you are right.
I missed the version in the kanji_mismatch directory, and missed that dot when i changed this a while ago.
And it looks like it should not be there in the two pre-2004 variant versions.

In the second row in the picture, on the left is the modern “IPAPMincho” font, with the extra dot, second is the older “MotoyaLMaru”, which is like the two “hyougai” variants. Those stay, the “plain” variant should get the extra dot.
![anki-](https://user-images.githubusercontent.com/1690429/37707024-d464a98c-2d01-11e8-8f52-7da0040a8e55.png)

**Comment by wtn** [comment]
Yes, [MJ028567](https://mojikiban.ipa.go.jp/search/detail/MJ028567) is the most correct form.

![mj028567](https://user-images.githubusercontent.com/35801/42101968-481a5620-7b8a-11e8-8fea-4ffae114ac77.png)

**Comment by benkasminbullock** [comment]
[IDS](https://github.com/cjkvi/cjkvi-ids) gives this as not having a dot in Japanese usage:

U+9957	饗	⿱鄉食[GT]	⿱郷食[J]	⿱鄕食[K]

Here the [J] means Japanese.

**Comment by wtn** [comment]
@benkasminbullock The IDS file is not authoritative. It's better to look at the code chart.
<img width="694" alt="u9957" src="https://user-images.githubusercontent.com/35801/115165626-60771700-a074-11eb-9a62-9a1aa741f187.png">

**Comment by benkasminbullock** [comment]
You say that it's better to look at the code chart, and you post an image of unknown provenance, and the above link in your previous post from 2018 is dead. The IDS chart is what is used by the committee which makes the Unicode Han tables (as far as I know), so it is actually authoritative in the sense that it is being used by the people who are deciding these things. Anyway, your response is not very useful without clear referencing.

**Comment by wtn** [comment]
The glyphs in the CJK ideograph code charts are the shapes endorsed by the national bodies. The IDS data file is not authoritative. It's merely one input the IRG uses in their duplicates check process.

The image from June 2018 is from the Moji Joho Kiban project. (The link broke because the project moved, but I've updated the link so it works again now.) The image from Apr 2021 is from the Unicode 13 code chart. The shapes for both are basically identical. But this character is on the 印刷標準字体 list, so both 鄕 & 郷 are acceptable. It's really up to whatever you want to do.

For a font example using a handwritten style, here's an image from the 漢検 dictionary:
![kanken](https://user-images.githubusercontent.com/35801/115168783-adadb580-a081-11eb-9cdd-b08020e9dd9e.jpg)

**Comment by benkasminbullock** [comment]
I suggest renaming kanji_mismatch/09957-Jinmei.svg to kanji/09957.svg with the following changes:

* Add the missing stroke numbers for stroke 21 and 22
* Add kvg:type for paths with ids s21 and s22
* Substitute the path of stroke 15 of kanji/09957.svg for stroke 16

The final suggestion is based on the form of the character in the PDF link.

I'm not sure what to rename the existing kanji/09957.svg, since there is already a "Hyougai" version of this which uses the food radical with a ム bottom part rather than the two horizontal lines used in kanji/09957.svg. Perhaps we can literally just call it kanji/09957-NoUpperDot.svg or something like that.

If this is acceptable I'll do the editing work by hand on the above character and rename it. If nobody speaks up I'll just go ahead, so please let me know if you have objections.
