### ISSUE TITLE
辟 and all kanji that include it: tare position is incorrect

### ISSUE THREAD

**Issue by Gnurou** [KanjiVG/kanjivg#18]
"tare" position is set to the parent element, which also creates one useless group.

**Comment by ospalh** [comment]
A grep for 辟 yielded
```
050fb-Kaisho.svg
050fb.svg
05288-Kaisho.svg
05288.svg
058c1-Kaisho.svg
058c1.svg
05b16-Kaisho.svg
05b16.svg
064d8-Kaisho.svg
064d8.svg
06a97-Kaisho.svg
06a97.svg
074a7-Kaisho.svg
074a7-KaishoVtLst.svg
074a7.svg
07513.svg
07656-Kaisho.svg
07656.svg
081c2-Kaisho.svg
081c2.svg
0859c-Kaisho.svg
0859c.svg
08617-Kaisho.svg
08617.svg
0895e-Kaisho.svg
0895e.svg
08b6c-Kaisho.svg
08b6c.svg
08e84-Kaisho.svg
08e84.svg
08f9f-Kaisho.svg
08f9f.svg
0907f-Kaisho.svg
0907f.svg
095e2-Kaisho.svg
095e2.svg
09739-Kaisho.svg
09739.svg
```

So, two down, 36 to do. Better than 38 to do.

**Comment by benkasminbullock** [comment]
What is the evidence that all of these are incorrect? Looking at 050fb.svg, the first element on @oslpalh's list, I find

```
<g id="kvg:050fb-g2" kvg:element="辟" kvg:position="right">
   <g id="kvg:050fb-g3" kvg:position="left">
   <g id="kvg:050fb-g4" kvg:element="尸" kvg:position="tare">
```
This does not seem to contain the original bug as given in the diff of the commit, so the bug report itself assuming these all contain the bug seems to be incorrect. I suggest closing this and reopening it for specific cases when they are found. Please reopen if not satisfied.
