### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by blastrock** [KanjiVG/kanjivg#186]
Hi,

I am the author of [Kakugo](https://github.com/blastrock/kakugo), an Android app that helps learning Japanese and that makes use of the kanjivg database. I have received a donation for my app and would like to redistribute part of it to upstream projects like this one (and I would do it for future donations as well). I couldn't find anything about financially supporting this project. Would you accept donations?

**Comment by Gnurou** [comment]
Hi! Thanks for considering donating! However KanjiVG is a multi-person effort and it is not clear where potential donations should go, therefore we do not take any. The joy of being a building block of great (and libre!) software like Kakugo is our reward. ;)

**Comment by DPTJKKVH** [comment]
@Gnurou I was literally moved to tears of joy when reading your message. Please know that your project in combination with other peoples work is helping a lot of people and I want to personally thank you and the team for that!

I use Kakugo for months and it is an essential part of my ongoing Japanese learning. It was recommended to me by a friend. I keep an eye on upstream projects of Kakugo purely out of interest. This is why I found this issue.

**Comment by Gnurou** [comment]
@DPTJKKVH Thanks for your kind words. Please make no mistake though, most of the work has been done by Ulrich Apel and his students. I have just advocated liberating it for the very selfish goal of using it for my own (now obsolete) project, and all things considered am doing a very poor job as a maintainer since I lack the qualifications to decide whether a fix is accurate or not, which results in the backlog of proposed fixes getting bigger and bigger. :(

But hearing about projects like Kakugo is very heartwarming, and gives me hope that we can get one or two competent scholars in the future to help managing KanjiVG. ^_^

**Comment by MarianVasile** [comment]
Alexandre, you did a wonderful job so far, picking up from Ulrich and his
students. I think many other people think the same and are quite grateful,
regardless of the backlog. This is a huge project to maintain. I've been
working on a toy project myself (drawing kanjis with multiple fingers at a
time), and KanjiVG is an essential part of what I'm trying to accomplish.
I'm now living in Japan and quickly becoming fluent in Japanese. My teacher
is a very knowledgeable person who can help if I have any questions, so I'm
thinking I should join in and contribute a little bit.

Sincerely,
Mark M. Vasile
