### ISSUE TITLE
Inconsistency in 黽 \u9EFD radical

### ISSUE THREAD

**Issue by SlugFiller** [KanjiVG/kanjivg#401]
Stroke 7 appears as 一:
<a href="https://github.com/KanjiVG/kanjivg/blob/master/kanji/09f07.svg"><img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/09f07.svg" width="327" height="327"></a>
<a href="https://github.com/KanjiVG/kanjivg/blob/master/kanji/09efd.svg"><img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/09efd.svg" width="327" height="327"></a>
<a href="https://github.com/KanjiVG/kanjivg/blob/master/kanji/07ac8.svg"><img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/07ac8.svg" width="327" height="327"></a>
<a href="https://github.com/KanjiVG/kanjivg/blob/master/kanji/08805.svg"><img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/08805.svg" width="327" height="327"></a>

Stroke 7 appears as ㇒:
<a href="https://github.com/KanjiVG/kanjivg/blob/master/kanji/07e69.svg"><img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/07e69.svg" width="327" height="327"></a>
<a href="https://github.com/KanjiVG/kanjivg/blob/master/kanji/09f08.svg"><img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/09f08.svg" width="327" height="327"></a>

**Comment by benkasminbullock** [comment]
I've spent about ten minutes trying to work out what you're reporting here without any success.

**Comment by benkasminbullock** [comment]
So to clarify you want the kvg:type field in these characters to be made more consistent?

**Comment by SlugFiller** [comment]
I don't have a specific solution in mind. I just wanted to point out it's inconsistent. Both the `kvg:type`, the actual drawing, and even the relation between the two. It just seems very random.

**Comment by benkasminbullock** [comment]
Regarding 08805, there is a variant with the other form here:

https://kanjivg.tagaini.net/viewer.html?file=08805-Hyougai.svg

I've changed the stroke type in 08805.svg:

https://github.com/KanjiVG/kanjivg/commit/5354311287d524640dac14a6c66df878741923c7

I don't know what to do about something seeming very random since I didn't decide these formats. It was all decided on the basis of the references at

https://kanjivg.tagaini.net/ref.html

If the references themselves are varying, it might be because the whole kanji writing system is somewhat inconsistent. 

So I am sorry but there is not much I can do about the inconsistency problems.

**Comment by benkasminbullock** [comment]
If there are no further fixable problems I'll mark this as closed.
