### ISSUE TITLE
Weird values for several "element" attribute values

### ISSUE THREAD

**Issue by syt0r** [KanjiVG/kanjivg#413]
There are several places where radicals are written with some encoding instead of characters:

源,CDP-8BC4, seems like it corresponds to 泉
愿,CDP-8BC4
原,CDP-8BC4
願,CDP-8BC4
穆,CDP-8BC4
曦,CDP-8DBA
縱,CDP8BB0
聳,CDP8BB0
慫,CDP8BB0
樅,CDP8BB0
從,CDP8BB0

Is these happened because some of them are missing in unicode? Is it intended?

**Comment by benkasminbullock** [comment]
> There are several places where radicals are written with some encoding instead of characters:
> 
> 源,CDP-8BC4, seems like it corresponds to 泉 愿,CDP-8BC4 原,CDP-8BC4 願,CDP-8BC4 穆,CDP-8BC4 曦,CDP-8DBA 縱,CDP8BB0 聳,CDP8BB0 慫,CDP8BB0 樅,CDP8BB0 從,CDP8BB0
> 
> Is these happened because some of them are missing in unicode? Is it intended?

Yes, this is because some of them are missing in Unicode. I did this change.

These are values used for kanji components taken from IDS. The descriptive file is here:

https://github.com/cjkvi/cjkvi-ids/blob/master/ids-cdp.txt

CDP stands for "Chinese Document Processing (lab)", see 

https://github.com/cjkvi/cjkvi-ids/blob/master/README.md

It looks like the hyphenation used is not consistent, so I'll check that.

**Comment by benkasminbullock** [comment]
> It looks like the hyphenation used is not consistent, so I'll check that.

This is done with d8dec7d20.

**Comment by benkasminbullock** [comment]
Thanks for bringing this up. Since I've answered the question, I'll close this issue. 

Please reopen it if you are not satisfied.

Theoretically questions should be asked on the KanjiVG mailing list so I haven't made "Discussions" available on the github repository, but the mailing list has become rather inactive. Anyway the mailing list would be the suggested place to ask further questions.
