### ISSUE TITLE
Suggestions for kanji with non-standard (simple unicode) radical form

### ISSUE THREAD

**Issue by Fulguritude** [KanjiVG/kanjivg#434]
Here are the kanji I've found with some non-standard first-order radicals.

0539f 原 : CDP-8BC4
05c08 專 : CDP-8BD0
05f9e 從 : CDP-8BB0
066b9 暹 : ⿱日隹
09083 邃 : ⿱穴㒸

I suppose this choice might be because there's no exact unicode representation for these first-order radical combinations (looking at glyphwiki this seems to be the case).

However, I'm thinking that maybe the choice of CDP-8BC4 over, say, ⿱白小, lacks consistency. Since the "top-bottom specifier" is more visual, I'd opt for this, rather than the CDP code. Same remark for CDP-8BB0 vs. ⿱从龰 .

CDP-8BD0 seems a bit more ambiguous. Would the top part be considered a variation on 虫 ? Maybe 叀 (\u53c0) ?

**Comment by benkasminbullock** [comment]
Yes this is inconsistent, and also incomplete. I added some of the CDP elements, and then I didn't complete this work, and also used some of the ideographic description character (IDC) based formats for some of the other things. I think I used the IDC formats before I started using the CDP elements, because I wasn't sure whether the CDP things were acceptable to this project. Then I realised that nobody seemed to be very interested in what I was doing, so I just went ahead and started using the CDP ones. The CDP elements are possibly more useful in my opinion since if we use IDC then we have to take account of a lot of details, but the CDP elements already have all the details very carefully taken care of for us. An example of that is the bottom thing you've posted. If we use CDP we don't have to worry about all of that stuff at all.

**Comment by benkasminbullock** [comment]
By the way what you call "radicals" we're calling "elements". Usually there is only one radical per kanji. So for anyone else reading this discussion, we are talking about the content of the kvg:element field, not the radical.

**Comment by benkasminbullock** [comment]
Another advantage of the CDP system is that the CDPs all have decompositions in the IDS database, so you can go from CDS to IDC format easily, by just substituting them, where they exist.

**Comment by benkasminbullock** [comment]
I'll close this discussion for the time being.
