### ISSUE TITLE
missing U+041F3 (䇳)

### ISSUE THREAD

**Issue by PANICBUTT0N** [KanjiVG/kanjivg#466]
alternate form of U+07B8B (箋)

**Comment by benkasminbullock** [comment]
Generally KanjiVG only covers the JIS kanji. You can find a list in https://www.asahi-net.or.jp/~ax2s-kmtn/ref/jisx0208.html. I've made a few additions of non-JIS entries, mostly because they were in the data but already added under a wrong code, but that is the basic list. 

If you want to add this, you're welcome to do so, but there isn't anybody actively adding non-Japanese characters at the moment, so unless you want to contribute this yourself, I'll close the issue and mark it as a request for a Chinese character. I don't actually have a good way to edit the graphical forms of the characters. Some people have discussed adding such a facility but it hasn't been done yet. The original kanjiVG inputs were done with Adobe Illustrator apparently, there is also Inkscape.
