### ISSUE TITLE
kvg:type and other attributes wrong.

### ISSUE THREAD

**Issue by ospalh** [KanjiVG/kanjivg#56]
I fixed the stroke numbers for  漕/06f15-KaishoVtLst.svg and 膿/081bf-KaishoVtLst.svg and while doing so noticed that some of the kvg:NN attributes not only in those files but also in the one i used as reference, 糟/07cdf-KaishoVtLst.svg are wrong.

Some strokes that are horizontal have `kvg:type="㇑"`, that is, the file claims they are vertical. The grouping (`<g kvg:element="NN">...</g>`) doesn't make a lot of sense, either.

I think this may effect several kanji variants with an "曲" element with the two verticals drawn last. That seem to be these:

```
05102-KaishoVtLst.svg
066f2-KaishoVtLst.svg
066f9-KaishoVtLst.svg
069fd-KaishoVtLst.svg
06f15-KaishoVtLst.svg
06fc3-KaishoVtLst.svg
079ae-KaishoVtLst.svg
07cdf-KaishoVtLst.svg
081bf-KaishoVtLst.svg
0825a-KaishoVtLst.svg
08276-KaishoVtLst.svg
08c4a-KaishoVtLst.svg
08ec6-KaishoVtLst.svg
08fb2-KaishoVtLst.svg
0906d-KaishoVtLst.svg
091b4-KaishoVtLst.svg
09c67-KaishoVtLst.svg
```

I don't want to muck around in there to fix them all by hand. (Some seem to be OK. I din't check all of them.)
Maybe this could be done by a (somewhat ad-hoc-ish) script of some sort.

**Comment by benkasminbullock** [comment]
Could you give links to the commit where you fixed the numbers? Without a link to see what you're referring to, it's very difficult to work that out.

**Comment by benkasminbullock** [comment]
I've been working on the angles using a computer program to check the type of the stroke against the actual angle made by the stroke. This is on this branch:

https://github.com/KanjiVG/kanjivg/tree/fix-angles

So far I have fixed several hundred incorrect cases, but I've been sticking to the 01235.svg files without the Kaisho etc. labels on them since I think those are the main files which everyone is using.

This problem occurred when the old SVG and XML directories were merged together. Some of the XML files did not match the SVG path information correctly but unfortunately the files were merged and the old formats deleted despite the production of many errors, which are found in the kanji_mismatch directory.

Unfortunately it's awfully difficult to go back and untangle them now after ten years or more of changes, and the new format with the complicated structure is very difficult to edit by hand without software tools. The old format would have made it much easier to fix this problem, since all that needed to be done was to rearrange lines of the XML file, which a non-programmer could do with any text editor. Now we have to untangle the groupings, renumber them, write back out in the correct format, etc. which is next to impossible without using a computer program.

**Comment by benkasminbullock** [comment]
I've been able to resolve all the problems with the 曲 element's stroke directions, but unfortunately the grouping of strokes within this is quite difficult to get right. 曲 has been constructed of 日 and 廾 subcomponents, and the 廾 subcomponent is further broken into 十 parts, and it's all done in a very complicated way with pieces of the 日 and 十 scattered around, with wrong groups attached to the strokes. As I said above, I think this was done when the XML and SVG stuff was merged together. Here is the pull request for fixing the stroke types:

https://github.com/KanjiVG/kanjivg/pull/269

I think the grouping will have to wait for now.
