### ISSUE TITLE
Stroke weights along with kvg:type

### ISSUE THREAD

**Issue by sauyon** [KanjiVG/kanjivg#95]
The issue with using CJK Stroke unicode characters for kvg:type, as far as I can see, is that they don't give any information about stroke weight. For example, the downward stroke in 十 and 下 have different endings - in 十 the brush is simply lifted to create a needle point, and in 下 it's stopped before before being lifted to create bone joint ending.

**Comment by leehericks** [comment]
Very late to the game here. Is this not purely a situation of the "stroke type" which few truly understand? KanjiVG itself are lines, not elaborately rendered brush strokes. stroke type, meaning of numbers of control points, etc needs to be well understood and documented in order to consider how the data can be used for rendering strokes.

**Comment by ospalh** [comment]
The difference is not just stroke type. In the example the two second strokes of [十](https://github.com/KanjiVG/kanjivg/blob/master/kanji/05341.svg?short_path=3863324#L41) and  [下](https://github.com/KanjiVG/kanjivg/blob/master/kanji/04e0b.svg?short_path=e03b14f#L44) is "[CJK STROKE S](http://www.fileformat.info/info/unicode/char/31d1/index.htm)".

Otoh, let’s put them in the  [XML](https://groups.google.com/d/msg/kanjivg/8U_RVOS2ZcY/uIe6J1K9Q-AJ).

**Comment by benkasminbullock** [comment]
In my opinion this request is not feasible to answer since there are different calligraphic styles for characters such as adding a hane for the downstroke of tree or not adding one depending on the school of calligraphy. For example the calligraphy school which I attended would add a hane to tree elements but other calligraphy schools do not.

**Comment by benkasminbullock** [comment]
If nobody else has anything else to add, may I suggest closing this as being outside the scope of KanjiVG, and not really a feasible request? 

Please reopen the issue if not satisfied.
